#Filename    : .cpanel.yml
#Location    : 
#Purpose     : For cpanel deployment
#Created     : 09/11/2019 02:23:08 by Spiderman
#Updated     : 09/11/2019 15:13:57 by Spiderman
#Changes     : 

---
deployment:
  tasks:
    - export APPPATH=/home/mountcarmelph/public_html/
    - export ASSETSPATH=/home/mountcarmelph/public_html/public/assets
    - /bin/cp -R application $APPPATH
    - /bin/cp -R public/assets/css $ASSETSPATH