#Filename    : config.yml
#Location    : .circleci/config.yml
#Purpose     : Config for circleci continues integration
#Created     : 09/11/2019 02:27:28 by Spiderman
#Updated     : 
#Changes     : 

version: 2
jobs:
  build:
    docker:
      - image: php:7.1-apache
    steps:
      - checkout
      #- run: <command>
  test:
    docker:
      - image: php:7.1-apache
    steps:
      - checkout
      #- run: <command>
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test