# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: php:7.1-apache
    steps:
      - checkout
      #- run: <command>
  test:
    docker:
      - image: php:7.1-apache
    steps:
      - checkout
      #- run: <command>
workflows:
  version: 2
  build_and_test:
    jobs:
      #- build
      #- test